name: Update snapshot tag
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: |
          ./mvnw -B --no-transfer-progress help:evaluate -Dexpression=project.version | grep -v INFO
          ./mvnw -B --no-transfer-progress clean verify

      - name: Update tag
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
        shell: bash
        run: |
          VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=project.version | grep -v INFO)
          echo $VERSION
          if [[ $VERSION == [.0-9]*-SNAPSHOT ]]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            echo "Update tag for $VERSION"
            git push origin :refs/tags/$VERSION
            git tag -f $VERSION
            git push --tags

            echo "Delete JitPack artifacts for tag"
            curl -X "DELETE" -u${JITPACK_TOKEN} https://jitpack.io/api/builds/dev.ebullient/quarkus-micrometer-extension/$VERSION
          fi
